FROM busybox AS base

ARG MESSAGE2="Goodbye, World!"
ENV MESSAGE1 "Hello, World!"
ENV MESSAGE2 ${MESSAGE2}
ENV MSG_FILE "message.txt"
ENV SHHH_SECRET "This is a secret!"
ENV SHHH_FILE "secret.txt"

RUN sleep 5 && \
    dd if=/dev/zero of=/tmp/bigfile bs=1024 count=1000 && \
    echo "${MESSAGE1}" >${MSG_FILE} && \
    echo "${SHHH_SECRET}" >${SHHH_FILE} && \
    rm ${SHHH_FILE} && \
    echo "${MESSAGE2}" >>${MSG_FILE} && \
    rm -f /tmp/bigfile


FROM busybox AS final

COPY --from=base /message.txt /message.txt
